project:
  type: website
  output-dir: _site

website:
  title: "RDA ambassador"
  description: "A starting point for connecting research communities with the Research Data Alliance (RDA), FAIR data practices, and domain-specific support."
  site-url: "https://www.rd-alliance.org/disciplines/rda-domain-ambassadors/"
  
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "Ambassadors"
        file: pages/ambassadors/index.qmd
      - text: "Resources"
        file: pages/resources/index.qmd
      - text: "News"
        file: pages/news/index.qmd
    right:
      - text: "FAQ"
        file: pages/faq/index.qmd
      - text: "Contribute"
        file: pages/contribute/index.qmd
      - icon: github
        href: https://github.com/
        
format:
  html:
    theme:
      - cosmo
      - styles.scss
    css: styles.scss
    toc: true
