project:
  type: website
  output-dir: _site

website:
  title: "RDA Domain Ambassadors"
  description: "Bridging the gap between the global Research Data Alliance community and specific research domains."
  site-url: "https://www.rd-alliance.org/disciplines/rda-domain-ambassadors/"
  
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "Ambassadors"
        file: pages/ambassadors/index.qmd
      - text: "Resources"
        file: pages/resources/index.qmd
    right:
      - text: "Contribute"
        file: pages/contribute/index.qmd
      - icon: github
        href: https://github.com/
        
format:
  html:
    theme:
      - cosmo
      - styles.scss
    css: styles.scss
    toc: true
